on track end:
	wait 40 tick
	getBVC() is set
	set {_r::*} to queue of event-bot in event-guild
	if {_r::*} is not set:
		if event-bot is not playing:
			send "Kolejka jest pusta. Wychodzę z kanału :wave:" to channel with id {v::play::kanal}.getId() with {bot::name}
			make {bot::name} leave vc

on track start:
	wait 30 tick
	send "Puszczam **`%track {bot::name} is playing in event-guild%`**" to channel with id {v::play::kanal}.getId() with {bot::name}