function getLastAuditLogs(typ: text) :: object:
	set {_g} to getGuild()
	loop ...event.getGuild().retrieveAuditLogs().cache(false):
		set {_v} to loop-value
		if "%{_v}.getType()%" is {_typ}:
			return {_v}

on message delete:
	set {_g} to getGuild()
	loop ...event.getGuild().retrieveAuditLogs().cache(false):
		set {_v} to loop-value
		log("%{_v}.getType()% is %{_typ}%")
		if "%{_v}.getType()%" is {_typ}:
			stop loop
	reply with "%{_v}%, %{_v}.getUser()%"