function getLastAuditLogs(typ: text) :: object:
	loop ...{_g}.retrieveAuditLogs().cache(false):
		set {_v} to loop-value
		if "%{_v}.getType()%" is {_typ}:
			return {_v}

on message delete:
	set {_g} to getGuild()
	loop ...event.getGuild().retrieveAuditLogs().cache(false):
		set {_v} to loop-value
		log("%{_v}.getType()% is %{_typ}%")
		stop loop
	reply with "%{_v}%, %{_v}.getUser()%"
	wait 10 tick
	set {_test} to getLastAuditLogs("DELETED_MESSAGE")
	reply with "%{_test}%, %{_test}.getUser()%"