options:
	cmd: update

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds

	set {command::{@cmd}::opis} to "Aktualizuje pliki"
	set {command::{@cmd}::kategoria} to "Deweloperskie"
	set {command::{@cmd}::uzycie} to "update"

import:
	java.io.BufferedReader
	java.io.IOException
	java.io.InputStreamReader

discord command {@cmd} [<text>]:
	aliases: cm,
	prefixes: "%{bot::prefix}%", "%mention tag of event-bot%"
	trigger:
		if arg-1 is not set:
			KamilAPI cmd error "Użyj: %{bot::prefix}%commit (last|update)"
		if arg-1 is not "last" or "update":
			KamilAPI cmd error "Użyj: %{bot::prefix}%commit (last|update)"

		if arg-1 is "last":
			reply with "Wczytywanie..." and store it in {v::update::botmsg}
			delete file "plugins/Skript/scripts/log.api"

			Runtime.getRuntime().exec("./home/kamil0024/Boty/0024B0T/plugins/commit.sh")

			set {_kek::*} to lines from file "plugins/Skript/scripts/log.api"
			edit {v::update::botmsg} to show "%{_kek::*}%"
			reply with "Eldo. %{_kek::*}%"

		KamilAPI add emote "green" to event-message
		delete {v::update::botmsg}
        # delete file "plugins\\Skript/temp.sh"
        # create file "plugins\\Skript/temp.sh"
        # write "%arg-1%" at line 1 to file "plugins\\Skript/temp.sh"
        # run script at "plugins\\Skript/temp.sh"
        # delete file "plugins\\Skript/temp.sh"

				#https://api.github.com/repos/KAMIL0024/0024B0T/commits
				#https://api.github.com/repos/KAMIL0024/0024B0T/commits/5e8b5936618902a2f705a604d0527b4a6a755ab8

				#zrobić coś przy użyciu "run sh cmd" i pozniej mozna pobrac z niego wyniki, patrz update skunity (https://forums.skunity.com/resources/skutilities.26/update?update=373)
				#bierzemy aktualny commit "git rev-parse HEAD"

		# TODO: To może wyjść kozak, jak uda się uzyskać last commita