options:
	cmd: commit

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds

	set {command::{@cmd}::opis} to "Aktualizuje pliki"
	set {command::{@cmd}::kategoria} to "Deweloperskie"
	set {command::{@cmd}::uzycie} to "commit (info|pull)"

import:
	java.io.BufferedReader
	java.io.InputStreamReader
	java.util.Arrays
	java.util.Objects
	java.util.concurrent.TimeUnit
	java.lang.System
	java.lang.ProcessBuilder

discord command {@cmd} [<text>]:
	aliases: git,
	prefixes: "%{bot::prefix}%", "%{bot::helpmention}%"
	trigger:
		if arg-1 is not set:
			KamilAPI cmd error "Użyj: %{bot::prefix}%commit (info|pull)"
		if arg-1 is not "info" or "pull":
			KamilAPI cmd error "Użyj: %{bot::prefix}%commit (info|pull)"
		set {_l} to getConfigEmote("loading")

		if arg-1 is "info":
			reply with "%{_l}% Ładuje..." and store it in {v::update::botmsg}

			set {_process} to new ProcessBuilder(Arrays.asList(System.getenv("SHELL"), "-c", "cd /home/kamil/P2WB0T/plugins/Skript/scripts/P2WB0T && git rev-parse --verify HEAD")).redirectErrorStream(true).start()
			{_process}.waitFor(2, TimeUnit.MINUTES!)
			set {_reader} to new BufferedReader(new InputStreamReader({_process}.getInputStream()))

			set {_builder} to ""
			if {_reader}.ready():
				loop 100 times:
					set {_line} to {_reader}.readLine()
					if {_line} is not set:
						stop loop

					set {_com} to "%{_line}%"
					stop loop
			{_process}.destroyForcibly()

			send a "GET" request to "https://api.github.com/repos/KAMIL0024/P2WB0T/commits/%{_com}%" with header "Authorization: token f07475480bd999564f70934b3c2a06e408678e11"
			map json body of last http response to {_r::*}
			loop {_r::files::*}:
				loop {_r::files::%loop-index%::*}:
					if loop-index-2 is "filename":
						add "%loop-value-2%%nl%" to {_edytowane::*}

			set {_xD} to "```%nl%%{_edytowane::*}%%nl%```"
			replace all ", " and " and " with "" in {_xD}

			set {_a} to a new embed
			create embed {_a}:
				set the colour of the embed to color of getColor(event-member)
				set the timestamp of embed to now
				set the footer of embed to footer with text "Commit info" and icon "%avatar of event-bot%"
				if {_edytowane::1} is set:
					set the description of embed to "Zmienione pliki:%nl% %{_xD}%"

				add field named "Aktualny commit" with value "[Klik](%{_r::parents::1::html_url}%)" to embed
				add field named "Author" with value "[%{_r::author::login}%](%{_r::author::html_url}%)" to embed
				add field named "Treść commita" with value "%{_r::commit::message}%" to embed
				add field named "Staty" with value "Dodane linijki: %{_r::stats::additions}%%nl%Usunięte linijki: %{_r::stats::deletions}%" to embed
				set the thumbnail of embed to "%{_r::author::avatar_url}%"

			edit {v::update::botmsg} to show {_a}
			edit {v::update::botmsg} to show " "
			KamilAPI add emote "green" to event-message of event-user
			delete {v::update::botmsg}
			stop

		if arg-1 is "pull":
			reply with "%{_l}% Aktualizuje pliki..." and store it in {v::update::botmsg}
			set {_process} to new ProcessBuilder(Arrays.asList(System.getenv("SHELL"), "-c", "cd /home/kamil/P2WB0T/plugins/Skript/scripts/P2WB0T && git pull")).redirectErrorStream(true).start()
			{_process}.waitFor(2, TimeUnit.MINUTES!)

			set {_reader} to new BufferedReader(new InputStreamReader({_process}.getInputStream()))

			set {_builder} to ""
			if {_reader}.ready():
				loop 100 times:
					set {_line} to {_reader}.readLine()
					if {_line} is not set:
						stop loop
					if {_builder} is set:
						set {_builder} to "%{_builder}%%{_line}%%nl%"
					else:
						set {_builder} to "%{_line}%%nl%"
					delete {_line}
			
			{_process}.destroyForcibly()

			set {_xD} to "```%nl%%{_builder}%%nl%```"
			replace all ", " and " and " with "" in {_xD}

			if {_xd} contains "Already up to date.":
				edit {v::update::botmsg} to show "Najnowsza aktualizacja jest już wgrana!"
				KamilAPI add emote "red" to event-message of event-user
				stop

			set {_a} to a new embed
			create embed {_a}:
				set the colour of the embed to color of getColor(event-member)
				set the timestamp of embed to now
				set the footer of embed to footer with text "Aktualizacja plików" and icon "%avatar of event-bot%"
				set the description of embed to "%{_xD}%"

			edit {v::update::botmsg} to show {_a}
			edit {v::update::botmsg} to show " "
			delete {v::update::botmsg}
			KamilAPI add emote "green" to event-message of event-user