options:
	cmd: eval

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds

discord command {@cmd} [<text>]:
	aliases: ev
	prefixes: "%{bot::prefix}%", "%mention tag of event-bot% "
	trigger:
		set {_arg} to arg-1
		if {_arg} is not set:
			KamilAPI cmd error "Użyj: %{bot::prefix}%eval (kod)" to event-message
		if {_arg}.contains("token"):
			KamilAPI cmd error "Nie wyciągniesz tokenu ezie" to event-message
		set {_now} to system millis
		replace all "```" with "" in {_arg}
		evaluate logging errors in {_error::*}: {_arg}
		set {_opis} to first element of ({_error::1} split at "(TuSKe")
		create embed:
			set the timestamp of embed to now
			set the footer of embed to footer with text "%difference between {_now} and system millis%ms"
			add field named ":inbox_tray: INPUT" with value "```js%nl%%{_arg}%%nl%```" to embed
			if {_error::*} is set:
				add field named ":skull: ERROR" with value "```js%nl%%{_opis}%%nl%```" to embed
				KamilAPI add emote "red" to event-message
				set the colour of the embed to red
			else:
				add field named ":outbox_tray: OUTPUT" with value "```js%nl%Wygenerowano!%nl%```" to embed
				KamilAPI add emote "green" to event-message
				set the colour of the embed to green
			send the last created embed to event-channel with event-bot