options:
	cmd: reboot

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds

	set {command::{@cmd}::opis} to "Restartuje bota"
	set {command::{@cmd}::kategoria} to "Deweloperskie"
	set {command::{@cmd}::uzycie} to "reboot"

discord command {@cmd} [<text>]:
	prefixes: "%{bot::prefix}%", "%{bot::helpmention}%" 
	trigger:
		reply with "Reloguje bota..."
		KamilAPI add emote "green" to event-message of event-user
		logout event-bot
		execute console command "sk reload 0024B0T/!core/"
		# TODO: Dodać po prostu `stop server`