options:
	cmd: reload

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds

	set {command::{@cmd}::opis} to "Zwykły reload"
	set {command::{@cmd}::kategoria} to "Deweloperskie"
	set {command::{@cmd}::uzycie} to "reload command <nazwa komendy>"

function reloadCommands(typ: numer=0, fot: text="") :: embed:
	set {_e} to a new embed

	set {_green} to getConfigEmote("green")
	set {_green} to getConfigEmote("red")
	set {_green} to getConfigEmote("reload")

	create embed {_e}:
		set the colour of the embed to green
		set the timestamp of embed to now
		if {_fot} is "":
			set the footer of embed to footer with text "Reload" and no icon
		else:
			set the footer of embed to footer with text "Reload | %{_fot}%" and no icon

		if {_typ} is 0:
			set the description of embed to "%{_reload}% Szukam pliku %nl%%{_red}% Unload %nl% %{_red}% Load"
		if {_typ} is 1:
			set the description of embed to "%{_red}% Szukam pliku (nie znaleziono pliku) %nl%%{_red}% Unload %nl% %{_red}% Load"
		if {_typ} is 2:
			set the description of embed to "%{_green}% Szukam pliku %nl%%{_reload}% Unload %nl% %{_red}% Load"
		if {_typ} is 3:
			set the description of embed to "%{_green}% Szukam pliku %nl%%{_green}% Unload %nl% %{_reload}% Load"
		if {_typ} is 4:
			set the description of embed to "%{_green}% Szukam pliku %nl%%{_green}% Unload %nl% %{_green}% Load"

	return {_e}

discord command {@cmd} [<text>]:
	aliases: r
	prefixes: "%{bot::prefix}%", "%{bot::helpmention}%" 
	trigger:
		set {_cmd} to arg-1
		if {_cmd} is not set:
			KamilAPI cmd error "%{bot::prefix}%%{command::{@cmd}::uzycie}%" to event-message
		set {_now} to system millis

		reply with reloadCommands(0) and store it in {_msg}

		set {_f::*} to files in dir "plugins/Skript/scripts/P2WB0T/commands/"
		loop {_f::*}:
			loop files in dir "%loop-value%/":
				set {_v} to "%loop-value-2%"
				set {_name} to last element of ({_v} split at "/")
				if {_name} contains "eval":
					set {_pwd} to last element of ("%loop-value-2%" split at "scripts/")
					stop loop

		if {_pwd} is not set:
			edit {_msg} to show reloadCommands(1)
			stop
		
		edit {_msg} to show reloadCommands(2)

		sync:
			execute console command "sk unload %{_pwd}%"
			edit {_msg} to show reloadCommands(3)
			execute console command "sk reload %{_pwd}%"
			edit {_msg} to show reloadCommands(4, "%difference between {_now} and system millis%ms")
 
		KamilAPI add emote "green" to event-message of event-user