options:
	cmd: reload

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds
	set {command::{@cmd}::opis} to "Reloaduje moduły."
	set {command::{@cmd}::kategoria} to "Deweloperskie"
	set {command::{@cmd}::uzycie} to "{@cmd} (commands|core) [moduł]"

function getCoreReloadEmbed(m: member, typ: number=0) :: embed:
	set {_l} to getConfigEmote("loading")
	set {_g} to getConfigEmote("green")
	set {_r} to getConfigEmote("red")

	set {_m} to a message builder
	
	if {_typ} is 0:
		append line "%{_r}% Szukanie modułu."
		append line "%{_r}% Reload modułu `!core`."
		append line "%{_r}% Zakończenie."
	
	if {_typ} is 1:
		append line "%{_g}% Szukanie modułu."
		append line "%{_r}% Reload modułu `!core`"
		append line "%{_r}% Zakończenie."

	if {_typ} is 2:
		append line "%{_g}% Szukanie modułu."
		append line "%{_g}% Reload modułu `!core`"
		append line "%{_r}% Zakończenie."	

	if {_typ} is 3:
		append line "%{_g}% Szukanie modułu."
		append line "%{_g}% Reload modułu `!core`"
		append line "%{_g}% Zakończenie."

	create embed:
		set the colour of the embed to color of getColor({_m})
		set the timestamp of embed to now
		set the footer of embed to footer with text "Reload"
		add field named "" with value "%{_m}%" to embed

	set {_e} to last created embed
	return {_e}

function getCommandReloadEmbed(m: member, tekst: text) :: embed:
	create embed:
		set the colour of the embed to color of getColor({_m})
		set the timestamp of embed to now
		set the footer of embed to footer with text "Reload"
		add field named "" with value "%{_tekst}%" to embed

	set {_e} to last created embed
	return {_e}

function coreAkcja(m: member, typ: number=0):
	set {_embed} to getCoreReloadEmbed({_m}, {_typ})
	edit {reload::botmsg} to show {_embed}
function commandAkcja(m: member, t: text, b: boolean=false):
	set {_embed} to getCommandReloadEmbed({_m}, {_t})
	edit {reload::botmsg} to show {_embed}
	if {_b} is true:
		delete {reload::botmsg}

discord command {@cmd} [<text>] [<text>]:
	aliases: reloads,
	prefixes: "%{bot::prefix}%", "%{bot::helpmention}%"
	trigger:
		set {_load} to getConfigEmote("loading")
		set {_g} to getConfigEmote("green")
		set {_r} to getConfigEmote("red")

		if arg-1 is not "commands" or "core":
			KamilAPI cmd error "Użyj: %{bot::prefix}%reload (commands|core) [module]"
		if arg-1 is "core":
			reply with "Wczytywanie..." and store it in {reload::botmsg}
			coreAkcja(event-member)
			edit {reload::botmsg} to show " "
			coreAkcja(event-member, 1)
			execute console command "sk reload 0024B0T/!core/"
			coreAkcja(event-member, 2)
			wait 10 tick
			coreAkcja(event-member, 3)
			delete {reload::botmsg}
			KamilAPI add emote "green" to event-message
		if arg-1 is "commands":
			if arg-2 is not set:
				set {_module} to "all"
			else:
				loop files in dir "plugins/Skript/scripts/0024B0T/commands/":
					set {_l} to loop-value
					set {_l} to last element of ({_l} split at "\")
					set {_modules::%{_l}%} to true

			reply with "Wczytywanie..." and store it in {reload::botmsg}
			if {_module} is "all":
				stop
			commandAkcja(event-member, "%{_load}% Szukam modułu%nl%%{_r}% Szukam komendy%nl%%{_r}% Reload komend (?/?)%nl%%{_r}% Kończe.")
			edit {reload::botmsg} to show " "
			if {_modules::%arg-2%} is not true:
				commandAkcja(event-member, "%{_r}% Szukam modułu (Nie znaleziono takiego modułu!)%nl%%{_r}% Szukam komendy%nl%%{_r}% Reload komend (?/?)%nl%%{_r}% Kończe.", true)
				stop
			commandAkcja(event-member, "%{_g}% Szukam modułu%nl%%{_load}% Szukam komendy%nl%%{_r}% Reload komend (?/?)%nl%%{_r}% Kończe.")
			loop files in dir "plugins/Skript/scripts/0024B0T/commands/%arg-2%/":
				set {_l} to loop-value
				set {_l} to last element of ({_l} split at "\")
				add {_l} to {_cmd::*}
			commandAkcja(event-member, "%{_g}% Szukam modułu%nl%%{_g}% Szukam komendy%nl%%{_load}% Reload komend (0/%size of {_cmd::*}%)%nl%%{_r}% Kończe.")

			set {_kurwa} to 0
			loop {_cmd::*}:
				execute console command "sk reload 0024B0T/commands/%arg-2%/%loop-value%"
				add 1 to {_kurwa}
				commandAkcja(event-member, "%{_g}% Szukam modułu%nl%%{_g}% Szukam komendy%nl%%{_load}% Reload komend (%{_kurwa}%/%size of {_cmd::*}%)%nl%%{_r}% Kończe.")

			commandAkcja(event-member, "%{_g}% Szukam modułu%nl%%{_g}% Szukam komend%nl%%{_g}% Reload komend (%{_kurwa}%/%size of {_cmd::*}%)%nl%%{_g}% Kończe.")
			KamilAPI add emote "green" to event-message