options:
	cmd: shell

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds

	set {command::{@cmd}::opis} to "Wykonuje kod w vps"
	set {command::{@cmd}::kategoria} to "Deweloperskie"
	set {command::{@cmd}::uzycie} to "{@cmd} <kod>"

import:
	java.io.BufferedReader
	java.io.InputStreamReader
	java.util.Arrays
	java.util.Objects
	java.util.concurrent.TimeUnit
	java.lang.System
	java.lang.ProcessBuilder

discord command {@cmd} [<text>]:
	prefixes: "%{bot::prefix}%", "%{bot::helpmention}%" 
	trigger:
		if event-user.getId() != "343467373417857025":
			KamilAPI cmd error "Komenda dostępna tylko dla Kamila" to event-message
	
		set {_arg} to arg-1
		replace all "```" with "" in {_arg}

		if {_arg} contains "rm" or "remove":
			KamilAPI cmd error "Nie usuniesz nic, sorka" to event-message

		reply with "%getConfigEmote(""loading"")% Wykonuję..." and store it in {_msg}

		set {_process} to new ProcessBuilder(Arrays.asList(System.getenv("SHELL"), "-c", {_arg})).redirectErrorStream(true).start()
		{_process}.waitFor(2, TimeUnit.MINUTES!)

		set {_reader} to new BufferedReader(new InputStreamReader({_process}.getInputStream()))

		set {_builder} to ""
		if {_reader}.ready():
			loop 100 times:
				set {_line} to {_reader}.readLine()
				if {_line} is not set:
					stop loop

				if {_builder} is set:
					set {_builder} to "%{_builder}%%{_line}%%nl%"
				else:
					set {_builder} to "%{_line}%%nl%"

				delete {_line}
		
		{_process}.destroyForcibly()

		set {_result} to {_builder}.toString()
		if {_result}.length() > 1993:
			set {_result} to {_result}.substring(0, 1980)

		edit {_msg} to show "```%nl%%{_result}%%nl%```"
		KamilAPI add emote "green" to event-message of event-user
