options:
	cmd: vps

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds

	set {command::{@cmd}::opis} to "Wyświetla specyikacje maszyny"
	set {command::{@cmd}::kategoria} to "Deweloperskie"
	set {command::{@cmd}::uzycie} to "vps"

import:
	pl.kamil0024.aapanel.Main

function aaPanel(url: string, action: string, token: string) :: string:
	return Main.getJSON({_url}, {_action}, {_token})

discord command {@cmd} [<text>]:
	prefixes: "%{bot::prefix}%", "%{bot::helpmention}%" 
	trigger:
		set {_json} to Main.getJSON("https://kamil0024.me:2137", "GetSystemTotal", "10r7KXYKnzzJXyFI4pCSxtUMCmWlvYjB")

		reply with "%{_json}%"

		KamilAPI add emote "green" to event-message of event-user

