options:
	cmd: vps

on script load:
	set {command::{@cmd}::poziom} to 10
	set {command::{@cmd}::cooldown} to 0 seconds

	set {command::{@cmd}::opis} to "Wyświetla specyikacje maszyny"
	set {command::{@cmd}::kategoria} to "Deweloperskie"
	set {command::{@cmd}::uzycie} to "vps"

import:
	pl.kamil0024.aapanel.Main as Panel
	java.lang.String
	java.util.Date

discord command {@cmd} [<text>]:
	prefixes: "%{bot::prefix}%", "%{bot::helpmention}%" 
	trigger:

		set {_url} to "https://kamil0024.me:2137/system?action=GetSystemTotal"
		log("url: %{_url}%")
		set {_timestamp} to "%new Date().getTime()%"
		set {_md5Sign} to Panel.getMd5("10r7KXYKnzzJXyFI4pCSxtUMCmWlvYjB")
		set {_temp} to "%{_timestamp}%%{_md5Sign}%"
		set {_token} to Panel.getMd5({_temp})

		set {_json} to "request_time=%{_timestamp}%&request_token=%{_token}%"

		set {_final} to Panel.sendPost({_url}, {_json})

		log(Panel.sendPost({_url}, {_json}))
		reply with "%{_final}%"

		KamilAPI add emote "green" to event-message of event-user

