# on guild message receive:
# 	if event-channel.getName() is "652262420470956042":
# 		if attachments of event-message is not set:
# 			set {_w} to difference between {v::obrazki::%event-user.getId()%::cooldown} and now
# 			if {_w} is set:
# 				if {_w} is less than 30 seconds:
# 					deleteMessage(event-message, 0)
# 					stop
# 			set {v::obrazki::%event-user.getId()%::cooldown} to now

# Później się przyda ;p