function addAkcje(karany: text, adm: text, typ: text, powod: text, nick: text, czas: text="null", end: text="null"):
	execute "SELECT id FROM akcje" in {bot::sql} and store result in {_kek::*}
	set {_id} to "%(size of {_kek::id::*})+1%"
	set {_now} to "%year%-%month%-%day% %hour%:%minute%:%second%"
	if {_czas} is "null":
		execute "INSERT INTO `akcje` (id,karany,nick,adm,typ,powod,now,aktywna) VALUES('%unsafe {_id}%', '%unsafe {_karany}%', '%unsafe {_nick}%' , '%unsafe {_adm}%', '%unsafe {_typ}%', '%unsafe getPowod({_powod})%', '%unsafe {_now}%', 'Tak')" in {bot::sql}
	else:
		execute "INSERT INTO `akcje` (id,karany,nick,adm,typ,powod,now,aktywna,czas,end) VALUES('%unsafe {_id}%', '%unsafe {_karany}%', '%unsafe {_nick}%' , '%unsafe {_adm}%', '%unsafe {_typ}%', '%unsafe getPowod({_powod})%', '%unsafe {_now}%', 'Tak' , '%unsafe {_czas}%', '%unsafe {_end}%')" in {bot::sql}