function getPoziomSlowny(n: number) :: text:
	if {_n} is 0:
		return "Użytkownik"
	if {_n} is 1:
		return "Ekipa"
	if {_n} is 2:
		return "Stażysta"
	if {_n} is 3:
		return "Pomocnik"
	if {_n} is 4:
		return "Moderator Discord"
	if {_n} is 5:
		return "Gł. Moderator Discord"
	if {_n} is 6:
		return "Moderator"
	if {_n} is 7:
		return "Administrator"
	if {_n} is 10:
		return "Deweloper"
	return "Poziom nieznany! Zgłoś to do administracji."