function AddEmbedPage(member: text, komenda: text, title: text="", description: text="", authorText: text="", authorUrl: text="", image: text="", thumbnail: text="", fieldTitle: strings="", fieldValue: strings=""):
	set {_u} to getUser({_member})
	set {_member} to (getGuild()).getMemberById({_u}.getId())
	set {_id} to {_member}.getUser().getId()
	{_id} is set 

	add 1 to {v::%{_id}%::EmbedBuilder::%{_komenda}%::stron}
	set {_s} to {v::%{_id}%::EmbedBuilder::%{_komenda}%::stron}

	set {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::title} to {_title}
	set {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::description} to {_description}
	set {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::authorText} to {_authorText}
	set {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::authorUrl} to {_authorUrl}
	set {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::image} to {_image}
	set {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::thumbnail} to {_thumbnail}

	loop {_fieldTitle::*}:
		add 1 to {_n}
		set {_field::%{_n}%::title} to loop-value
	loop {_fieldValue::*}:
		add 1 to {_num}
		set {_field::%{_num}%::value} to loop-value

	loop (size of {_field::*} times):
		loop {_field::%loop-value%::*}:
			set {_kurwa} to loop-value-1
			set {_ind} to loop-index
			set {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::field::%{_kurwa}%::%{_ind}%} to loop-value-2
		
	loop {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::*}:
		if loop-value is "":
			delete {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::%loop-index%}

function DeleteEmbedPage(xd: text, komenda: text):
	delete {v::%{_xd}%::StronyEmbeda::*}
	delete {v::%{_xd}%::EmbedBuilder::%{_komenda}%::*}

function GetEmbedPage(member: text, komenda: text, s: text) :: embed:
	set {_u} to getUser({_member})
	set {_member} to (getGuild()).getMemberById({_u}.getId())
	set {_id} to {_member}.getUser().getId()
	{_id} is set 
	{v::%{_id}%::EmbedBuilder::%{_komenda}%::stron} is set
	if {_s} > {v::%{_id}%::EmbedBuilder::%{_komenda}%::stron}:
		stop
	if {_s} < {v::%{_id}%::EmbedBuilder::%{_komenda}%::stron}:
		stop
	create embed:
		set the colour of the embed to color of getColor({_member})
		set the title of embed to title with text {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::title}
		set the timestamp of embed to now
		set the footer of embed to footer with text "(%{_s}%/%{v::%{_id}%::EmbedBuilder::%{_komenda}%::stron}%)" and no icon
	
		set the description of embed to {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::description}

		set the author info of the embed to author named {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::authorText} with no url and no icon
		if {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::authorUrl} is set:
			set the author info of the embed to author named {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::authorText} with no url and icon {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::authorUrl}
		
		loop (size of {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::field::%{_kurwa}%::*}) times:
			set {_value} to {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::field::%loop-value%::value}
			set {_title} to {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::field::%loop-value%::title}

			add field named {_title} with value {_value} to embed
	
		set the image of embed to {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::image}
		set the thumbnail of embed to {v::%{_id}%::EmbedBuilder::%{_komenda}%::%{_s}%::thumbnail}
	set {_e} to last created embed
	return {_e}

effect KamilAPI set page for %message% to %boolean% with %user% and (cmd|command) %text%:
	trigger:
		set {_msg} to expr-1
		set {_bol} to expr-2
		set {_user} to expr-3
		set {_cmd} to expr-4
		set {_id} to {_user}.getId()

		if {_bol} is false:
			KamilAPI clear reaction from {_msg}
			DeleteEmbedPage({_id}, {_cmd})
			stop
		if {_bol} is true:
			{v::%{_id}%::EmbedBuilder::%{_cmd}%::stron} is set
			set {v::%{_id}%::StronyEmbeda::msg} to {_msg}
			set {v::%{_id}%::StronyEmbeda::cmd} to {_cmd}
			set {v::%{_id}%::StronyEmbeda::strona} to 1
			loop "⏮", "◀", "⏹", "▶", "⏭", "🔢":
				add emote "%loop-value%" to {_msg} with {bot::name}
			set {_embed} to GetEmbedPage({_id}, {_cmd}, "1")
			edit {_msg} to show {_embed}
			edit {_msg} to show " "

on reaction add:
	set {_id} to event-user.getId()
	{v::%{_id}%::StronyEmbeda::msg} is event-message
	remove event-emote added by event-user from event-message

	set {_e} to "%event-emote%"
	set {_user} to event-user
	set {_cmd} to {v::%{_id}%::StronyEmbeda::cmd}

	if {_e} is "⏹":
		KamilAPI clear reaction from event-message
		DeleteEmbedPage({_id}, {_cmd})
		stop
		
	if {_e} is "⏮":
		set {_strona} to 1
	if {_e} is "⏭":
		set {_strona} to {v::%{_id}%::EmbedBuilder::%{_cmd}%::stron}
	if {_e} is "◀":
		set {_strona} to {v::%{_id}%::StronyEmbeda::strona}-1
	if {_e} is "▶":
		set {_strona} to {v::%{_id}%::StronyEmbeda::strona}+1

	if {_strona} is set:
		if {_strona} > {v::%{_id}%::EmbedBuilder::%{_cmd}%::stron}:
			stop
		if {_strona} < 1:
			stop
		set {_embed} to GetEmbedPage({_id}, {_cmd}, "%{_strona}%")
		edit event-message to show {_embed}
		set {v::%{_id}%::StronyEmbeda::strona} to {_strona}